version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptimekuma
    volumes:
      - ${MOUNTPATH}:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${PORT}:3001
    restart: always
